import Mathlib.CategoryTheory.Category.Basic
import Mathlib.CategoryTheory.Limits.Shapes.End
import Mathlib.CategoryTheory.Opposites

/-!
# Endoprofunctors and Bimodules (Initial Layer)

This file introduces a lightweight project-level API for endoprofunctors.

Mathlib status:

- Mathlib provides general ends/coends (`CategoryTheory.Limits.Shapes.End`).
- Mathlib does not currently provide a dedicated `Profunctor` structure in category theory.

So, to stay consistent with Mathlib conventions, we model profunctors as bifunctors
`Dᵒᵖ ⥤ C ⥤ Type`.

This file contains:

- `Profunctor C D := Dᵒᵖ ⥤ C ⥤ Type`,
- `Bimodule C := Profunctor C C`,
- a concrete quotient presentation of horizontal composition in `Type`,
- the identity bimodule `HomBimod`.

Implementation note on the quotient model:

- `CompObj` uses `Quot` on a generating relation `CompRel`.
- In Lean, `Quot r` identifies points by the equivalence relation generated by `r`.
- So this is the standard explicit coend presentation in `Type`.
- Tradeoff: later constructions must be shown well-defined via `Quot.induction`
  / `Quot.sound`, which adds proof overhead.
-/

namespace LeanColoredCoalgebras
namespace Endoprofunctor

open CategoryTheory
open Opposite

universe w uC vC uD vD

/--
A profunctor from `D` to `C`, represented in Mathlib style as a bifunctor
`Dᵒᵖ ⥤ C ⥤ Type w`.
-/
abbrev Profunctor (C : Type uC) [Category.{vC} C]
    (D : Type uD) [Category.{vD} D] :=
  Dᵒᵖ ⥤ C ⥤ Type w

namespace Profunctor

variable {C : Type uC} [Category.{vC} C]
variable {D : Type uD} [Category.{vD} D]

/-- Evaluation of a profunctor at objects `(X, Y)`. -/
abbrev Obj (P : Profunctor (C := C) (D := D)) (X : D) (Y : C) : Type w :=
  (P.obj (op X)).obj Y

/--
Action of a profunctor on morphisms, contravariant in `D` and covariant in `C`.

`map f g : P(X',Y) → P(X,Y')` for `f : X ⟶ X'`, `g : Y ⟶ Y'`.
-/
def map (P : Profunctor (C := C) (D := D))
    {X X' : D} {Y Y' : C} (f : X ⟶ X') (g : Y ⟶ Y') :
    Obj P X' Y → Obj P X Y' :=
  fun e => (P.obj (op X)).map g (((CategoryTheory.Functor.map P f.op).app Y) e)

@[simp] lemma map_id_apply (P : Profunctor (C := C) (D := D))
    (X : D) (Y : C) (e : Obj P X Y) :
    map P (𝟙 X) (𝟙 Y) e = e := by
  simp [map]

@[simp] lemma map_comp_apply (P : Profunctor (C := C) (D := D))
    {X X' X'' : D} {Y Y' Y'' : C}
    (f : X ⟶ X') (f' : X' ⟶ X'')
    (g : Y ⟶ Y') (g' : Y' ⟶ Y'')
    (e : Obj P X'' Y) :
    map P (f ≫ f') (g ≫ g') e = map P f g' (map P f' g e) := by
  dsimp [map]
  simp only [Functor.map_comp, FunctorToTypes.comp, FunctorToTypes.map_comp_apply]
  refine congrArg ((P.obj (op X)).map g') ?_
  exact (congrArg (fun k => k (((CategoryTheory.Functor.map P f'.op).app Y) e))
    ((CategoryTheory.Functor.map P f.op).naturality g)).symm

end Profunctor

/-- A bimodule on `C` is a profunctor `C ⇸ C`. -/
abbrev Bimodule (C : Type uC) [Category.{vC} C] :=
  Profunctor (C := C) (D := C)

section Composition

variable {C : Type uC} [Category.{vC} C]

/-- The sigma-type used in coend-style horizontal composition of bimodules. -/
abbrev CompData (P Q : Bimodule (C := C)) (X Y : C) :=
  Σ Z : C, Profunctor.Obj P Z Y × Profunctor.Obj Q X Z

/--
The generating relation for composition of bimodules:
a middle morphism can be absorbed either by `P` or by `Q`.

This is only the generating relation; `CompObj` quotients by the equivalence closure.
-/
inductive CompRel (P Q : Bimodule (C := C)) (X Y : C) :
    CompData P Q X Y → CompData P Q X Y → Prop where
  | glue {Z Z' : C} (f : Z ⟶ Z')
      (p : Profunctor.Obj P Z' Y) (q : Profunctor.Obj Q X Z) :
      CompRel P Q X Y
        ⟨Z, (Profunctor.map P f (𝟙 Y) p, q)⟩
        ⟨Z', (p, Profunctor.map Q (𝟙 X) f q)⟩

/--
Coend-style horizontal composition object for bimodules, implemented as a quotient.

In `Type`, this is the explicit presentation of `∫^{z} P(z, Y) × Q(X, z)`.
-/
def CompObj (P Q : Bimodule (C := C)) (X Y : C) :=
  Quot (CompRel P Q X Y)

namespace CompObj

variable (P Q : Bimodule (C := C)) (X Y : C)

/-- Constructor of `CompObj` from a chosen middle object and a pair of elements. -/
def mk (Z : C) (p : Profunctor.Obj P Z Y) (q : Profunctor.Obj Q X Z) :
    CompObj P Q X Y :=
  Quot.mk _ ⟨Z, (p, q)⟩

/--
Core quotient relation: absorbing `f` on the `P` side equals absorbing it on the `Q` side.
-/
lemma glue {Z Z' : C} (f : Z ⟶ Z')
    (p : Profunctor.Obj P Z' Y) (q : Profunctor.Obj Q X Z) :
    mk P Q X Y Z (Profunctor.map P f (𝟙 Y) p) q =
      mk P Q X Y Z' p (Profunctor.map Q (𝟙 X) f q) :=
  Quot.sound (CompRel.glue f p q)

end CompObj

end Composition

/--
The identity bimodule `Hom_C`, used as the horizontal unit in the bicategory of profunctors.
-/
def HomBimod (C : Type uC) [Category.{vC} C] : Bimodule (C := C) where
  obj X :=
    { obj Y := X.unop ⟶ Y
      map f h := h ≫ f
      map_id Y := by
        ext h
        simp
      map_comp f g := by
        ext h
        simp [Category.assoc] }
  map f :=
    { app := fun Y h => f.unop ≫ h
      naturality := by
        intro Y Y' g
        ext h
        simp [Category.assoc] }
  map_id X := by
    ext Y h
    simp
  map_comp f g := by
    ext Y h
    simp [Category.assoc]

end Endoprofunctor
end LeanColoredCoalgebras
